# Generated by Django 2.1.11 on 2019-10-25 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_position_profileposition'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoExactProfilePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exactposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productoexactprofileposition_exactposition', to='persona.ProfilePosition')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productoexactprofileposition_producto', to='general.Producto')),
            ],
        ),
    ]
