# Generated by Django 2.1.11 on 2019-10-25 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_productoexactprofileposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoexactprofileposition',
            name='producto',
        ),
        migrations.AddField(
            model_name='productoexactprofileposition',
            name='movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productoexactprofileposition_movimiento', to='general.MovimientoGeneral'),
        ),
    ]
