# Generated by Django 2.1.11 on 2019-11-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20191025_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='numero_de_parte_dos',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='numero_de_parte_uno',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
