# Generated by Django 2.1.11 on 2019-11-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20191109_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroParte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_parte', models.CharField(max_length=70)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_numero_de_parte', to='general.Producto')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='numeroparte',
            unique_together={('producto', 'numero_de_parte')},
        ),
    ]
