# Generated by Django 2.1.11 on 2019-11-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20191127_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='numero_de_parte_dos',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='numero_de_parte_uno',
        ),
    ]
