# Generated by Django 2.1.11 on 2019-11-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20191128_1226'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('nombre',)},
        ),
    ]
