# Generated by Django 2.1.7 on 2019-02-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
