# Generated by Django 2.1.7 on 2019-03-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'medidas',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateField()),
                ('no_folio', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('dot', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='llantas.Marca')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='llantas.Medida')),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'posiciones',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'status',
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'tipo de movimientos',
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='posicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='llantas.Posicion'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='llantas.Status'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='llantas.TipoMovimiento'),
        ),
    ]
