# Generated by Django 2.1.7 on 2019-03-11 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('llantas', '0002_auto_20190311_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimiento',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
