# Generated by Django 2.1.7 on 2019-03-12 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        ('llantas', '0003_auto_20190311_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creadror_del_movimiento', to='persona.Profile'),
        ),
    ]
