# Generated by Django 2.1.7 on 2019-03-14 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        ('llantas', '0004_movimiento_creador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_folio', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones_grales', models.TextField(blank=True, null=True)),
                ('fecha_vale', models.DateField()),
                ('fecha_created', models.DateTimeField(auto_now_add=True)),
                ('fecha_edited', models.DateTimeField(auto_now=True)),
                ('persona_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persona_asociada', to='persona.Profile')),
            ],
            options={
                'verbose_name_plural': 'Vales',
            },
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='no_folio',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='vale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vale_asociado', to='llantas.Vale'),
        ),
    ]
