# Generated by Django 2.1.7 on 2019-03-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llantas', '0005_auto_20190314_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='tipo_movimiento',
        ),
        migrations.AddField(
            model_name='vale',
            name='tipo_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='llantas.TipoMovimiento'),
        ),
    ]
