# Generated by Django 2.1.7 on 2019-03-14 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        ('llantas', '0006_auto_20190314_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='vale',
            name='creador_vale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creador_vale', to='persona.Profile'),
        ),
    ]
