# Generated by Django 2.1.7 on 2019-03-15 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llantas', '0007_vale_creador_vale'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='tipo_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='llantas.TipoMovimiento'),
        ),
    ]
