# Generated by Django 2.1.7 on 2019-03-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llantas', '0008_movimiento_tipo_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
