# Generated by Django 2.1.7 on 2019-03-18 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llantas', '0010_auto_20190318_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='llanta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='llantas.Llanta'),
        ),
    ]
