# Generated by Django 2.1.7 on 2019-03-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llantas', '0013_vale_con_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionMovimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='importacion/')),
                ('fecha_created', models.DateTimeField(auto_now_add=True)),
                ('fecha_edited', models.DateTimeField(auto_now=True)),
                ('procesado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'importacion de movimientos',
            },
        ),
    ]
