# Generated by Django 2.1.7 on 2019-03-23 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('llantas', '0014_importacionmovimientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntovale',
            name='fecha_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adjuntovale',
            name='fecha_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
