# Generated by Django 2.1.7 on 2019-04-02 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        ('llantas', '0015_auto_20190323_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='llanta',
            name='porciento_vida',
            field=models.PositiveSmallIntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='permisionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisionario_llanta', to='persona.Profile'),
        ),
    ]
