# Generated by Django 2.1.11 on 2019-11-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llantas', '0016_auto_20190402_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='vale',
            name='vale_llantas',
            field=models.BooleanField(default=True),
        ),
    ]
