# Generated by Django 2.1.11 on 2020-02-06 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_position_profileposition'),
        ('llantas', '0017_vale_vale_llantas'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlantaBasura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot', models.CharField(blank=True, max_length=100, null=True)),
                ('porciento_vida', models.PositiveSmallIntegerField(blank=True, default=100, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='llantas.Marca')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='llantas.Medida')),
                ('posicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='llantas.Posicion')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='llantas.Status')),
            ],
            options={
                'verbose_name_plural': 'llantas basura',
            },
        ),
        migrations.CreateModel(
            name='MovimientoBasura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creadror_del_movimiento_basura', to='persona.Profile')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destino_del_movimiento_basura', to='persona.Profile')),
                ('llanta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='llantas.LlantaBasura')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origen_del_movimiento_basura', to='persona.Profile')),
                ('permisionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisionario_llanta_basura', to='persona.Profile')),
                ('tipo_movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='llantas.TipoMovimiento')),
            ],
        ),
        migrations.CreateModel(
            name='ValeBasura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones_grales', models.TextField(blank=True, null=True)),
                ('fecha_vale', models.DateField()),
                ('fecha_created', models.DateTimeField(auto_now_add=True)),
                ('fecha_edited', models.DateTimeField(auto_now=True)),
                ('vale_llantas', models.BooleanField(default=True)),
                ('creador_vale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creador_vale_basura', to='persona.Profile')),
                ('persona_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tractor_asociado_basura', to='persona.Profile')),
                ('tipo_movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='llantas.TipoMovimiento')),
                ('vale_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='llantas.Vale')),
            ],
            options={
                'verbose_name_plural': 'Vales de Basura',
            },
        ),
        migrations.AddField(
            model_name='movimientobasura',
            name='vale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vale_asociado_basura', to='llantas.ValeBasura'),
        ),
    ]
