# Generated by Django 3.1.6 on 2021-02-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llantas', '0018_auto_20200205_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='medida',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='posicion',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medida',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tipomovimiento',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
